require 'swagger_helper'

RSpec.describe 'token_revoke', type: :request do
  path '/oauth/revoke' do
    post 'Token revoke API generated by module &#39;Email login&#39;' do
      tags 'token_revoke'
      consumes 'application/json'
      parameter name: :params, in: :body, schema: {
        type: :object,
        properties: {
          token: {
            type: :string,
            example: 'string'
          }

        }
      }
      response '403', 'token_revoke' do
        examples 'application/json' => {
        }
        let(:params) { { grant_type: 'password' } }
        run_test! do |response|
          expect(response.status).to eq(403)
        end
      end
    end
  end
end
