require 'swagger_helper'

RSpec.describe 'token_creation', type: :request do
  path '/oauth/token' do
    post 'Token creation API generated by module &#39;Email login&#39;' do
      tags 'token_creation'
      consumes 'application/json'
      parameter name: :params, in: :body, schema: {
        type: :object,
        properties: {
          grant_type: {
            type: :string,
            example: 'string'
          },

          client_id: {
            type: :string,
            example: 'string'
          },

          client_secret: {
            type: :string,
            example: 'string'
          },

          scope: {
            type: :string,
            example: 'string'
          },

          email: {
            type: :string,
            example: 'string'
          },

          password: {
            type: :string,
            example: 'string'
          }

        }
      }
      response '401', 'token_creation' do
        examples 'application/json' => {
          'error' => 'string',

          'error_description' => 'string'

        }
        let(:params) { { grant_type: 'password' } }
        run_test! do |response|
          expect(response.status).to eq(401)
        end
      end
    end
  end
end
